###create project
POST  http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name" : "Parsa",
    "last_name" : "Mokhtarpour",
    "skills" : ["programming" , "NODEJS" , "EXPRESSJS"]
}